all:  
	gcc myNetLib.c    client.c      -o client
	gcc myNetLib.c    mirror-exec.c -o mirror-exec
	gcc myNetLib.c    subMirror.c   -o subMirror
	gcc myNetLib.c    auditor.c     -o auditor

  
clean:
	rm -f client  mirror-exec  subMirror  auditor  *.copy
